addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"        % "0.14.2")
addSbtPlugin("com.github.sbt" % "sbt-dynver"          % "5.1.0")
addSbtPlugin("com.github.sbt" % "sbt-javaagent"       % "0.1.8")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.11.1")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"        % "2.5.2")
